### PR TITLE
[ENH] Improve container configuration

### PR DESCRIPTION
**Pull request by DESm1th**
This pull request addresses the duplication in the containers folder

- Replace the dashboard.env and database.env files in the `containers/devel` and `containers/prod` folders with a single copy in `containers` 50873c358eccb8eba9e7e6de6e8c01f158780227
- Replace the dockerfiles in `containers/devel` and `containers/prod` with a single multistage dockerfile in `containers` 053536472d68f761bea68a299e8144fec76fa7cc
- Update the docker compose files to build from the new multistage dockerfile and better handle the volumes 1b4ab433f70fb8b87690053a58056aba1850a360
- Update the installation instructions to address the changes aeb0db46aabf6cdd6c2d7a3de3f1b35c43970bd5

### CODE REVIEW

**Review by jerdra — CHANGES_REQUESTED** [review]
Yesss @DESm1th!! I love these changes w/multi-stage targets cleaning up the setup process! 

One minor comment! 

In the `installation.rst` document Would it make sense to move the development section up before the full installation bit and maybe collapse the docker section into one? 

Just to avoid repeated content so we don't have to edit two places for any changes!

**Comment by DESm1th** [comment]
That's a good point! I'll try to rewrite that later today to get rid of the duplication. Thanks Jer :)

**Review by josephmje — APPROVED** [review]
Really neat @DESm1th! I had no idea multi-stage builds were a thing!

**Comment by DESm1th** [comment]
@jerdra I reorganized the install instructions! Does it look ok?

**Review by jerdra — APPROVED** [review]
Looks great, thanks for the changes :)

**Pull request merged**
